### ISSUE TITLE
Responsive menu doesn't work

### ISSUE THREAD

**Issue by joaovpmamede** [minuscode/minuscode.github.io#23]
Clicking on menu anchor doesn't open the navigation.

**Comment by dcruz** [comment]
Problem caused by commit 0e3f458

Faulty line:
https://github.com/minuscode/minuscode.github.io/blame/master/css/src/ui/_page.scss#L17

Fix incoming

**Comment by csergiuu** [comment]
I've already fixed that bug and made pull request.
