### ISSUE TITLE
[ABOUT] Ligature / Font rendering

### ISSUE THREAD

**Issue by miguelm** [minuscode/minuscode.github.io#49]
it seems there is issue with "flexible", see the following [link](https://www.evernote.com/shard/s531/sh/5b1f9859-303d-482d-802e-ec8daa907dfd/c74394ecdcd1e73c)

**Comment by csergiuu** [comment]
It's a font issue, any suggestions?  @dcruz

**Comment by miguelm** [comment]
@dcruz seems there's no apparent solution for this right now, though open for suggestions
